In [104]:
import pandas as pd
import numpy as np
from pathlib import Path
import os
from glob import glob

In [142]:
path_a = "E:\\github_clone\\human-activity-recognition\\data\\CollectedData\\person01\\cycling\\Accelerometer.csv"
path_g= "E:\\github_clone\\human-activity-recognition\\data\\CollectedData\\person01\\cycling\\Gyroscope.csv"

In [143]:
df1 = pd.read_csv("E:\\github_clone\\human-activity-recognition\\data\\CollectedData\\person01\\cycling\\Accelerometer.csv")
df2 = pd.read_csv(path_g)

In [144]:
df1.head()

,timestamp,timeIntervalSince1970,x,y,z
0,2023-10-14 13:54:15.450 +0000,1.697292e+09,0.057907,0.006638,-1.035995
1,2023-10-14 13:54:15.460 +0000,1.697292e+09,0.070953,0.012756,-1.024368
2,2023-10-14 13:54:15.470 +0000,1.697292e+09,0.062805,0.010101,-1.025208
3,2023-10-14 13:54:15.480 +0000,1.697292e+09,0.053345,0.009033,-1.013779
4,2023-10-14 13:54:15.490 +0000,1.697292e+09,0.061066,0.007034,-1.038651

In [145]:
df2.head()

,timestamp,timeIntervalSince1970,x,y,z
0,2023-10-14 13:54:15.465 +0000,1.697292e+09,0.046209,-0.027273,-0.005676
1,2023-10-14 13:54:15.475 +0000,1.697292e+09,-0.009909,0.029105,-0.011199
2,2023-10-14 13:54:15.494 +0000,1.697292e+09,0.005584,0.016366,-0.007149
3,2023-10-14 13:54:15.504 +0000,1.697292e+09,-0.007305,0.006338,-0.004910
4,2023-10-14 13:54:15.514 +0000,1.697292e+09,-0.025383,0.032794,-0.008421

In [164]:
dt = pd.DataFrame({'acc_x_mean':[df1['x'].mean()],
                   'acc_y_mean':[df1['y'].mean()],
                   'acc_z_mean':[df1['z'].mean()],
                   'acc_x_std':[df1['x'].std()],
                   'acc_y_std':[df1['y'].std()],
                   'acc_z_std':[df1['z'].std()],
                   'acc_x_max':[df1['x'].max()],
                   'acc_y_max':[df1['y'].max()],
                   'acc_z_max':[df1['z'].max()],
                   'acc_x_min':[df1['x'].min()],
                   'acc_y_min':[df1['y'].min()],
                   'acc_z_min':[df1['z'].min()],
                   'gyro_x_mean':[df2['x'].mean()],
                   'gyro_y_mean':[df2['y'].mean()],
                   'gyro_z_mean':[df2['z'].mean()],
                   'gyro_x_std':[df2['x'].std()],
                   'gyro_y_std':[df2['y'].std()],
                   'gyro_z_std':[df2['z'].std()],
                   'gyro_x_max':[df2['x'].max()],
                   'gyro_y_max':[df2['y'].max()],
                   'gyro_z_max':[df2['z'].max()],
                   'gyro_x_min':[df2['x'].min()],
                   'gyro_y_min':[df2['y'].min()],
                   'gyro_z_min':[df2['z'].min()],
                   'activity':[path_a.split('\\')[-2]]
                   })

In [165]:
dt

,acc_x_mean,acc_y_mean,acc_z_mean,acc_x_std,acc_y_std,acc_z_std,acc_x_max,acc_y_max,acc_z_max,acc_x_min,...,gyro_x_std,gyro_y_std,gyro_z_std,gyro_x_max,gyro_y_max,gyro_z_max,gyro_x_min,gyro_y_min,gyro_z_min,activity
0,-0.230548,-0.453565,-0.84009,0.491319,0.371673,0.278898,0.759598,0.642914,-0.026642,-2.266571,...,1.121614,1.463906,1.488188,4.561753,4.601133,4.594489,-2.752184,-5.391257,-5.437454,cycling

In [98]:
path1 = "E:\\github_clone\\human-activity-recognition\\data\\CollectedData\\person01\\running\\Accelerometer.csv"
path2 = "E:\\github_clone\\human-activity-recognition\\data\\CollectedData\\person01\\running\\Gyroscope.csv"

In [99]:
df_acc = pd.read_csv(path1)
df_gyr = pd.read_csv(path2)

In [100]:
def sample_dict(df1, df2, path):
    d = {'acc_x_mean':df1['x'].mean(),
        'acc_y_mean':df1['y'].mean(),
        'acc_z_mean':df1['z'].mean(),
        'acc_x_std':df1['x'].std(),
        'acc_y_std':df1['y'].std(),
        'acc_z_std':df1['z'].std(),
        'acc_x_max':df1['x'].max(),
        'acc_y_max':df1['y'].max(),
        'acc_z_max':df1['z'].max(),
        'acc_x_min':df1['x'].min(),
        'acc_y_min':df1['y'].min(),
        'acc_z_min':df1['z'].min(),
        'gyro_x_mean':df2['x'].mean(),
        'gyro_y_mean':df2['y'].mean(),
        'gyro_z_mean':df2['z'].mean(),
        'gyro_x_std':df2['x'].std(),
        'gyro_y_std':df2['y'].std(),
        'gyro_z_std':df2['z'].std(),
        'gyro_x_max':df2['x'].max(),
        'gyro_y_max':df2['y'].max(),
        'gyro_z_max':df2['z'].max(),
        'gyro_x_min':df2['x'].min(),
        'gyro_y_min':df2['y'].min(),
        'gyro_z_min':df2['z'].min(),
        'activity':path.split('\\')[-2]
                   }
    return d

In [166]:
def read_data(df, path):
    l = glob(os.path.join(path, "*", "*"))
    for i in range(0,len(l),2):
        print(l[i])
        d1, d2 = pd.read_csv(l[i]), pd.read_csv(l[i+1])
        dic = sample_dict(d1, d2, l[i])
        print(dic['activity'])
        df = df.append(dic, ignore_index=True)
    return df

In [167]:
temp = '../data/CollectedData/person02/'

In [168]:
dt = read_data(dt, temp)

../data/CollectedData/person02\running\Accelerometer.csv
running
../data/CollectedData/person02\walking\Accelerometer.csv
walking

C:\Users\Ernest\AppData\Local\Temp\ipykernel_17680\3042428951.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dic, ignore_index=True)
C:\Users\Ernest\AppData\Local\Temp\ipykernel_17680\3042428951.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dic, ignore_index=True)

In [169]:
dt = read_data(dt, '../data/CollectedData/person01/')

../data/CollectedData/person01\cycling\Accelerometer.csv
cycling
../data/CollectedData/person01\running\Accelerometer.csv
running
../data/CollectedData/person01\walking\Accelerometer.csv
walking

C:\Users\Ernest\AppData\Local\Temp\ipykernel_17680\3042428951.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dic, ignore_index=True)
C:\Users\Ernest\AppData\Local\Temp\ipykernel_17680\3042428951.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dic, ignore_index=True)
C:\Users\Ernest\AppData\Local\Temp\ipykernel_17680\3042428951.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dic, ignore_index=True)

In [162]:
dt

,acc_x_mean,acc_y_mean,acc_z_mean,acc_x_std,acc_y_std,acc_z_std,acc_x_max,acc_y_max,acc_z_max,acc_x_min,...,gyro_x_std,gyro_y_std,gyro_z_std,gyro_x_max,gyro_y_max,gyro_z_max,gyro_x_min,gyro_y_min,gyro_z_min,activity
0,-0.230548,-0.453565,-0.840090,0.491319,0.371673,0.278898,0.759598,0.642914,-0.026642,-2.266571,...,1.121614,1.463906,1.488188,4.561753,4.601133,4.594489,-2.752184,-5.391257,-5.437454,cycling
1,-0.305674,-0.001172,-1.101150,0.743001,0.549519,0.775614,1.057312,1.233780,0.720947,-3.323059,...,2.404731,2.004671,2.637449,6.085533,6.546100,7.098913,-6.592543,-6.724548,-6.683323,running
2,-0.233536,0.026147,-1.055474,0.973989,1.075888,1.017781,4.176178,4.284393,2.408768,-3.732452,...,2.601897,1.626558,2.652911,9.253407,7.950536,8.296871,-10.232458,-7.315168,-9.695805,walking
3,-0.230548,-0.453565,-0.840090,0.491319,0.371673,0.278898,0.759598,0.642914,-0.026642,-2.266571,...,1.121614,1.463906,1.488188,4.561753,4.601133,4.594489,-2.752184,-5.391257,-5.437454,cycling
4,0.102541,-0.014250,-1.155009,0.429281,0.476667,0.724133,2.832382,2.137680,0.950043,-1.569122,...,2.659421,1.751432,2.412158,9.602736,10.335733,9.578442,-8.683516,-6.928000,-8.818892,running